test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# digitalocean:
#   service: S3
#   endpoint: https://obs.ap-southeast-2.myhuaweicloud.com 
#   access_key_id: <%= ENV['DIGITALOCEAN_ACCESS_KEY_ID'] || Rails.application.credentials.dig(:digitalocean, :access_key_id) %>
#   secret_access_key: <%= ENV['DIGITALOCEAN_SECRET_ACCESS_KEY'] || Rails.application.credentials.dig(:digitalocean, :secret_access_key) %>
#   region: <%= ENV['DIGITALOCEAN_REGION'] || Rails.application.credentials.dig(:digitalocean, :region) || 'sgp1' %>
#   bucket: <%= ENV['DIGITALOCEAN_BUCKET'] || Rails.application.credentials.dig(:digitalocean, :bucket) %>

huaweicloud:
  service: S3
  endpoint: https://obs.ap-southeast-2.myhuaweicloud.com 
  access_key_id: <%= ENV['HUAWEICLOUD_ACCESS_KEY_ID'] || Rails.application.credentials.dig(:huawei, :access_key_id) %>
  secret_access_key: <%= ENV['HUAWEICLOUD_SECRET_ACCESS_KEY'] || Rails.application.credentials.dig(:huawei, :secret_access_key) %>
  region: <%= ENV['HUAWEICLOUD_REGION'] || Rails.application.credentials.dig(:huawei, :region) || 'ap-southeast-2' %>
  bucket: <%= ENV['HUAWEICLOUD_BUCKET'] || Rails.application.credentials.dig(:huawei, :bucket) %>

huawei:
  service: S3
  endpoint: https://obs.ap-southeast-2.myhuaweicloud.com
  access_key_id: <%= Rails.application.credentials.dig(:huawei, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:huawei, :secret_access_key) %>
  region: AP-Bangkok
  bucket: <%= Rails.application.credentials.dig(:huawei, :bucket) %>

# Huawei OBS connection config for importing newspapers from various source buckets
# Note: bucket name is dynamic and provided by PdfSource model
huawei_import:
  service: S3
  endpoint: https://obs.ap-southeast-2.myhuaweicloud.com
  access_key_id: <%= Rails.application.credentials.dig(:huawei, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:huawei, :secret_access_key) %>
  region: AP-Bangkok
  force_path_style: false

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
